# Generated by Django 3.2.5 on 2021-07-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='about',
            name='lien',
        ),
    ]
